### ISSUE TITLE
Internal error on command:"T0"

### ISSUE THREAD

**Issue by rqtqp** [TypQxQ/KTC#42]
Hi, I have DYI plotter using Klipper, Moonraker (latest versions), python 3.9.2
I have no heaters, fans
I tried to make KTC work with the config provided in examples but every time I get Internal Error.

Please find console log and klippy.log attached:

```
11:54 Internal error on command:"T1"
11:54 Internal error on command:"_SET_ACTIVE_TOOL"
11:54 Internal error on command:"KTC_T1"
11:54 Klipper state: Shutdown
11:54 KTC Toolchanger  is in ERROR state.
11:54 KTC Tool 1 failed to select: KTC is in error state
11:54 KTC Tool 1 Selecting.
11:54 T1
11:53 Unknown tool is active and can't be deselected.
11:53 Unknown tool is active and can't be deselected.
11:53 TOOL_DROPOFF
11:53 Unknown tool already mounted.Can't automatically deselect unknown tool before selecting new tool.
11:53 KTC Toolchanger  is in ERROR state.
11:53 KTC Tool 0 failed to select: Unknown tool already mounted.Can't automatically deselect unknown tool before selecting new tool.
11:53 Unknown tool already mounted.Can't automatically deselect unknown tool before selecting new tool.
11:53 KTC Tool 0 Selecting.
11:53 KTC_T0
11:53 KTC_TOOL 1 (T1):
	- state: CONFIGURED
	- extruder state: 0
	- Active time: 0s
	- Standby time: 0s
	- Selected time: 0s
	- Time spent selecting: 0s
	- Time spent deselecting:                     0s
11:53 KTC_TOOL 0 (T0):
	- state: CONFIGURED
	- extruder state: 0
	- Active time: 0s
	- Standby time: 0s
	- Selected time: 0s
	- Time spent selecting: 0s
	- Time spent deselecting:                     0s
11:53 KTC Debugging Heaters:
11:53 KTC_DEBUG_TOOLS
11:51 KTC Tools registered:
	(KTC_T0 ) 0
	(KTC_T1 ) 1
	(KTC_T-1) tool_none
	(KTC_T-2) tool_unknown
11:51 KTC_TOOLS_DISPLAY
11:50 G28
11:50 Klipper state: Disconnect
11:50 FIRMWARE_RESTART
```
[klippy.log](https://github.com/user-attachments/files/18006253/klippy.log)

```
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/pi/klipper/klippy/webhooks.py", line 436, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/pi/klipper/klippy/gcode.py", line 230, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 212, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 227, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 212, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 140, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 189, in cmd
    self.template.run_gcode_from_command(kwparams)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 227, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 212, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 140, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/ktc_tool.py", line 210, in select
    raise e from e
  File "/home/pi/klipper/klippy/extras/ktc_tool.py", line 103, in select
    self._ktc.confirm_ready_for_toolchange(self)
  File "/home/pi/klipper/klippy/extras/ktc.py", line 933, in confirm_ready_for_toolchange
    raise ValueError("KTC is in error state")
ValueError: KTC is in error state
```

Looking forward for your support.
Thanks in advance.

**Comment by TypQxQ** [comment]
Hi! Could you also attach the ktc.log
You should find it in the same location as klippy.log.

**Comment by rqtqp** [comment]
Please find the excerpt from ktc.log

```
09:50:08 Klipper disconnected! Closing KTC log.
09:50:12 - - TRACE: Loading persisted state.
09:50:12 - - TRACE: No toolchangers defined. Creating default toolchanger.
09:50:12 - - TRACE: Performance profile for _config_default_toolchanger:
                  447 function calls in 0.005 seconds
         
            Ordered by: cumulative time
         
            ncalls  tottime  percall  cumtime  percall filename:lineno(function)
                 1    0.000    0.000    0.005    0.005 /home/soda/klipper/klippy/extras/ktc.py:158(_config_default_toolchanger)
                 1    0.000    0.000    0.003    0.003 /home/soda/klipper/klippy/klippy.py:90(load_object)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_log.py:163(trace)
                 1    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1432(info)
                 1    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1561(_log)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_toolchanger.py:289(load_config_prefix)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_toolchanger.py:28(__init__)
                 1    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1587(handle)
                 1    0.000    0.000    0.001    0.001 /usr/lib/python3.9/genericpath.py:16(exists)
                 1    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1641(callHandlers)
                 1    0.001    0.001    0.001    0.001 {built-in method posix.stat}
                 3    0.000    0.000    0.001    0.000 /usr/lib/python3.9/logging/__init__.py:935(handle)
                 2    0.000    0.000    0.001    0.000 /home/soda/klipper/klippy/klippy.py:81(lookup_objects)
                 2    0.000    0.000    0.001    0.000 /home/soda/klipper/klippy/klippy.py:85(<listcomp>)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_base.py:403(__init__)
09:50:12 - - TRACE: Performance profile for _config_tools:
                  88 function calls in 0.001 seconds
         
            Ordered by: cumulative time
         
            ncalls  tottime  percall  cumtime  percall filename:lineno(function)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc.py:237(_config_tools)
                 1    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/klippy.py:81(lookup_objects)
                 1    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/klippy.py:85(<listcomp>)
                74    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
                 2    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc_tool.py:53(toolchanger)
                 4    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc_tool.py:49(toolchanger)
                 2    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
                 2    0.000    0.000    0.000    0.000 {method 'values' of 'dict' objects}
                 1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
         
         
09:50:12 - - TRACE: Performance profile for configure_inherited_params:
                  56 function calls in 0.001 seconds
         
            Ordered by: cumulative time
         
            ncalls  tottime  percall  cumtime  percall filename:lineno(function)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc.py:324(configure_inherited_params)
                 1    0.001    0.001    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_base.py:181(configure_inherited_params)
                 2    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc_base.py:327(persistent_state)
                 2    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc_base.py:345(_get_type_for_persistent_state)
                13    0.000    0.000    0.000    0.000 {built-in method builtins.getattr}
                 3    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/klippy.py:75(lookup_object)
                10    0.000    0.000    0.000    0.000 {built-in method builtins.setattr}
                 9    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
                 2    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc.py:369(state)
                 6    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
                 2    0.000    0.000    0.000    0.000 /home/soda/klipper/klippy/extras/ktc_base.py:316(state)
                 2    0.000    0.000    0.000    0.000 /usr/lib/python3.9/typing.py:1333(cast)
                 1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
                 1    0.000    0.000    0.000    0.000 {built-in method builtins.len}
                 1    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
09:50:12 - - TRACE: Setting standby_to_powerdown_delay to 600 for tool 0 with state 0
09:50:12 - - TRACE: Setting standby_to_powerdown_delay to 600 for tool 1 with state 0
09:50:12 - - TRACE: Performance profile for _recursive_configure_inherited_attributes:
                  486 function calls in 0.004 seconds
         
            Ordered by: cumulative time
         
            ncalls  tottime  percall  cumtime  percall filename:lineno(function)
                 1    0.000    0.000    0.004    0.004 /home/soda/klipper/klippy/extras/ktc.py:290(_recursive_configure_inherited_attributes)
                 2    0.000    0.000    0.003    0.002 /home/soda/klipper/klippy/extras/ktc_tool.py:63(configure_inherited_params)
                 2    0.000    0.000    0.003    0.001 /home/soda/klipper/klippy/extras/ktc_heater.py:219(standby_to_powerdown_delay)
                 2    0.000    0.000    0.002    0.001 /home/soda/klipper/klippy/extras/ktc_log.py:163(trace)
                 2    0.000    0.000    0.002    0.001 /usr/lib/python3.9/logging/__init__.py:1432(info)
                 2    0.000    0.000    0.002    0.001 /usr/lib/python3.9/logging/__init__.py:1561(_log)
                 2    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1587(handle)
                 2    0.000    0.000    0.001    0.001 /usr/lib/python3.9/logging/__init__.py:1641(callHandlers)
                 6    0.000    0.000    0.001    0.000 /usr/lib/python3.9/logging/__init__.py:935(handle)
                 3    0.001    0.000    0.001    0.000 /home/soda/klipper/klippy/extras/ktc_base.py:181(configure_inherited_params)
                 1    0.000    0.000    0.001    0.001 /home/soda/klipper/klippy/extras/ktc_toolchanger.py:65(configure_inherited_params)
                 4    0.000    0.000    0.001    0.000 /home/soda/klipper/klippy/extras/ktc_log.py:838(emit)
                 2    0.000    0.000    0.001    0.000 /usr/lib/python3.9/logging/__init__.py:1546(makeRecord)
                 2    0.000    0.000    0.001    0.000 /usr/lib/python3.9/logging/__init__.py:278(__init__)
                 6    0.000    0.000    0.001    0.000 /usr/lib/python3.9/queue.py:185(put_nowait)
09:50:12 KTC Log Ready
09:51:46 KTC Tools registered:
         (KTC_T0 ) 0
         (KTC_T1 ) 1
         (KTC_T-1) tool_none
         (KTC_T-2) tool_unknown
09:53:03 KTC Debugging Heaters:
09:53:03 KTC_TOOL 0 (T0):
         - state: CONFIGURED
         - extruder state: 0
         - Active time: 0s
         - Standby time: 0s
         - Selected time: 0s
         - Time spent selecting: 0s
         - Time spent deselecting:                     0s
         
09:53:03 KTC_TOOL 1 (T1):
         - state: CONFIGURED
         - extruder state: 0
         - Active time: 0s
         - Standby time: 0s
         - Selected time: 0s
         - Time spent selecting: 0s
         - Time spent deselecting:                     0s
         
09:53:23 KTC Tool 0 Selecting.
09:53:23 Unknown tool already mounted.Can't automatically deselect unknown tool before selecting new tool.
09:53:23 KTC Tool 0 failed to select: Unknown tool already mounted.Can't automatically deselect unknown tool before selecting new tool.
09:53:23 KTC Toolchanger  is in ERROR state.
09:54:06 KTC Tool 1 Selecting.
09:54:06 KTC Tool 1 failed to select: KTC is in error state
09:54:06 KTC Toolchanger  is in ERROR state.
```

**Comment by TypQxQ** [comment]
According to the ktc.log there it belives a tool is selected. Try deselecting by calling `KTC_DESELECT_ALL`.

**Comment by rqtqp** [comment]
```
16:49 Unknown tool is active and can't be deselected.
16:49 KTC_DESELECT_ALL
```
Forgot to mention about this output:
I'm a bit cofused, is it ok?
```
16:49 KTC Tools registered:
(KTC_T0 ) 0
(KTC_T1 ) 1
(KTC_T-1) tool_none
(KTC_T-2) tool_unknown
16:49 KTC_TOOLS_DISPLAY
```

**Comment by rqtqp** [comment]
```
[ktc_toolchanger Default]
init_mode = ON_START

init_gcode:
    KTC_TOOLCHANGER_DISENGAGE TOOLCHANGER={myself.name}
    KTC_SET_ACTIVE_TOOL TOOL={ktc.TOOL_NONE}
    KTC_SET_STATE TOOLCHANGER={myself.name} STATE=READY
    RESPOND MSG="Toolchanger {myself.name} initialized unlocked, without tool"
```
helps to get rid on unknown tool and fixes everything )
